---
- name: Install software
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop:
    - ulogd2
  loop_control:
    loop_var: item
# ulogd config
- name: Confogure /etc/ulogd.conf to log to syslog only, part 1
  ansible.builtin.lineinfile:
    path: /etc/ulogd.conf
    regexp: '^(|#)stack=.*,emu1:LOGEMU'
    line: '#stack=log1:NFLOG,base1:BASE,ifi1:IFINDEX,ip2str1:IP2STR,print1:PRINTPKT,emu1:LOGEMU'
    create: false
    firstmatch: true
  when: ansible_virtualization_type == 'lxc'
  notify: Reload ulogd2
- name: Configure /etc/ulogd.conf to log to syslog only, part 2
  ansible.builtin.blockinfile:
    path: /etc/ulogd.conf
    insertafter: '^#stack'
    marker: '### ansible {mark} FAI'
    block: 'stack=log1:NFLOG,base1:BASE,ifi1:IFINDEX,ip2str1:IP2STR,print1:PRINTPKT,sys1:SYSLOG'
    create: false
  when: ansible_virtualization_type == 'lxc'
  notify: Reload ulogd2
...
